// <auto-generated />
using System;
using Fridges.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fridges.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250805122750_InitialMigrate")]
    partial class InitialMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fridges.Domain.Enities.Fridge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Capacity")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsFreezer")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fridges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5820c2b-fc43-4a62-a717-b0eecb90e0b5"),
                            Capacity = (short)5,
                            IsFreezer = false,
                            Name = "Атлант"
                        },
                        new
                        {
                            Id = new Guid("1aa76163-5ad2-4b36-a9cf-b04dd154a73f"),
                            Capacity = (short)7,
                            IsFreezer = true,
                            Name = "Samsung"
                        });
                });

            modelBuilder.Entity("Fridges.Domain.Enities.Products.MeatProducts", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.ToTable("MeatProducts");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("0fa2a1f6-fc70-45e5-82e4-e25aa6f49b95"),
                            IsFrozen = true,
                            Type = 2
                        });
                });

            modelBuilder.Entity("Fridges.Domain.Enities.Products.MilkProducts", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<float>("FatPercent")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.ToTable("MilkProducts");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("96a7c8a5-9517-4a39-a990-0145b17b7f4c"),
                            FatPercent = 3.5f,
                            Type = "Milk"
                        });
                });

            modelBuilder.Entity("Fridges.Domain.Enities.Products.PlantProducts", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOrganic")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.ToTable("PlantProducts");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("a7e58b11-d61a-4df3-9cb3-2d1272a99115"),
                            IsOrganic = true,
                            Type = "Tomato"
                        });
                });

            modelBuilder.Entity("Fridges.Domain.Enities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Expiration")
                        .HasColumnType("date");

                    b.Property<Guid>("FridgeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFresh")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Release")
                        .HasColumnType("date");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.Property<Guid?>("meatProductsProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("milkProductsProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("plantProductsProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FridgeId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("meatProductsProductId");

                    b.HasIndex("milkProductsProductId");

                    b.HasIndex("plantProductsProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0fa2a1f6-fc70-45e5-82e4-e25aa6f49b95"),
                            Expiration = new DateOnly(2025, 7, 20),
                            FridgeId = new Guid("1aa76163-5ad2-4b36-a9cf-b04dd154a73f"),
                            IsFresh = true,
                            ProductTypeId = 3,
                            Release = new DateOnly(2025, 7, 1),
                            Weight = 0.5f
                        },
                        new
                        {
                            Id = new Guid("96a7c8a5-9517-4a39-a990-0145b17b7f4c"),
                            Expiration = new DateOnly(2025, 7, 18),
                            FridgeId = new Guid("e5820c2b-fc43-4a62-a717-b0eecb90e0b5"),
                            IsFresh = true,
                            ProductTypeId = 4,
                            Release = new DateOnly(2025, 7, 2),
                            Weight = 1.2f
                        },
                        new
                        {
                            Id = new Guid("a7e58b11-d61a-4df3-9cb3-2d1272a99115"),
                            Expiration = new DateOnly(2025, 8, 1),
                            FridgeId = new Guid("1aa76163-5ad2-4b36-a9cf-b04dd154a73f"),
                            IsFresh = true,
                            ProductTypeId = 11,
                            Release = new DateOnly(2025, 7, 5),
                            Weight = 0.3f
                        });
                });

            modelBuilder.Entity("Fridges.Domain.Enities.Recipe.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Говядина",
                            category = "0"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Свинина",
                            category = "0"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Курица",
                            category = "0"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Молоко",
                            category = "0"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Сыр",
                            category = "0"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Йогурт",
                            category = "0"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Брокколи",
                            category = "0"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Картофель",
                            category = "0"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Яблоко",
                            category = "0"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Хлеб",
                            category = "0"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Томаты",
                            category = "0"
                        });
                });

            modelBuilder.Entity("Fridges.Domain.Enities.Recipe.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22b1b28a-7712-4f3a-a4b2-0b5d79c6c230"),
                            Instructions = "Some instructions...",
                            title = "Simple chicken pasta"
                        });
                });

            modelBuilder.Entity("Fridges.Domain.Enities.Recipe.RecipeProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("unitType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80ac650f-2158-4d5d-a38f-16e1287b89d4"),
                            ProductTypeId = 3,
                            Quantity = 0.4f,
                            RecipeId = new Guid("22b1b28a-7712-4f3a-a4b2-0b5d79c6c230"),
                            unitType = "kg"
                        },
                        new
                        {
                            Id = new Guid("96e30ad8-94d9-4dc0-9f79-8a13adfe6de9"),
                            ProductTypeId = 4,
                            Quantity = 500f,
                            RecipeId = new Guid("22b1b28a-7712-4f3a-a4b2-0b5d79c6c230"),
                            unitType = "ml"
                        },
                        new
                        {
                            Id = new Guid("b5384463-0404-42dc-b949-f0b33916efaa"),
                            ProductTypeId = 11,
                            Quantity = 200f,
                            RecipeId = new Guid("22b1b28a-7712-4f3a-a4b2-0b5d79c6c230"),
                            unitType = "g"
                        });
                });

            modelBuilder.Entity("Fridges.Domain.Enities.Products.MeatProducts", b =>
                {
                    b.HasOne("Fridges.Domain.Enities.Products.Product", "Product")
                        .WithOne()
                        .HasForeignKey("Fridges.Domain.Enities.Products.MeatProducts", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Fridges.Domain.Enities.Products.MilkProducts", b =>
                {
                    b.HasOne("Fridges.Domain.Enities.Products.Product", "Product")
                        .WithOne()
                        .HasForeignKey("Fridges.Domain.Enities.Products.MilkProducts", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Fridges.Domain.Enities.Products.PlantProducts", b =>
                {
                    b.HasOne("Fridges.Domain.Enities.Products.Product", "Product")
                        .WithOne()
                        .HasForeignKey("Fridges.Domain.Enities.Products.PlantProducts", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Fridges.Domain.Enities.Products.Product", b =>
                {
                    b.HasOne("Fridges.Domain.Enities.Fridge", "Fridge")
                        .WithMany("Products")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fridges.Domain.Enities.Recipe.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fridges.Domain.Enities.Products.MeatProducts", "meatProducts")
                        .WithMany()
                        .HasForeignKey("meatProductsProductId");

                    b.HasOne("Fridges.Domain.Enities.Products.MilkProducts", "milkProducts")
                        .WithMany()
                        .HasForeignKey("milkProductsProductId");

                    b.HasOne("Fridges.Domain.Enities.Products.PlantProducts", "plantProducts")
                        .WithMany()
                        .HasForeignKey("plantProductsProductId");

                    b.Navigation("Fridge");

                    b.Navigation("ProductType");

                    b.Navigation("meatProducts");

                    b.Navigation("milkProducts");

                    b.Navigation("plantProducts");
                });

            modelBuilder.Entity("Fridges.Domain.Enities.Recipe.RecipeProduct", b =>
                {
                    b.HasOne("Fridges.Domain.Enities.Recipe.ProductType", "ProductType")
                        .WithMany("RecipeProducts")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fridges.Domain.Enities.Recipe.Recipe", "Recipe")
                        .WithMany("RecipeProducts")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Fridges.Domain.Enities.Fridge", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Fridges.Domain.Enities.Recipe.ProductType", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("RecipeProducts");
                });

            modelBuilder.Entity("Fridges.Domain.Enities.Recipe.Recipe", b =>
                {
                    b.Navigation("RecipeProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
